### ISSUE TITLE
"Determining duration" during session initialization slow

### ISSUE THREAD

**Issue by ralphpeterson** [scratchrealm/isa#2]
I think for this step we are determining the duration by loading in the audio and calculating the length — maybe it's faster to use openCV to grab video metadata?

[e.g.](https://www.folkstalk.com/2022/10/get-video-duration-opencv-python-with-code-examples.html)
```
import cv2

cap = cv2.VideoCapture("./video.mp4")
fps = cap.get(cv2.CAP_PROP_FPS)      # OpenCV2 version 2 used "CV_CAP_PROP_FPS"
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration = frame_count/fps       #in seconds

cap.release()
```

**Comment by magland** [comment]
I was thinking it might be useful to be able to load datasets that do not have video.

**Comment by ralphpeterson** [comment]
Makes sense. Also, we need to load the audio anyways, so there's no way around this.
