### ISSUE TITLE
Pose annotation carry over

### ISSUE THREAD

**Issue by ralphpeterson** [scratchrealm/isa#3]
It would be great if the pose annotated on frame n-1 could be easily added to frame n. Most of the time the animal will be in a similar position and this would speed up annotating.

Maybe we can add a button to "Add previous pose". Then the user can drag points to make fine adjustments.

**Comment by magland** [comment]
@ralphpeterson There is now a "USE PREVIOUS_POSE" button. Please close the issue once you confirm it works.

**Comment by ralphpeterson** [comment]
Works great, thanks! One small additional request — can selecting "USE PREVIOUS POSE" also auto accept the vocalization?

**Comment by magland** [comment]
> can selecting "USE PREVIOUS POSE" also auto accept the vocalization?

Done. Closing.
