### ISSUE TITLE
Labels for pose annotations

### ISSUE THREAD

**Issue by ralphpeterson** [scratchrealm/isa#4]
Perhaps we can add a legend to the help menu or add small text attached to each annotation to differentiate head/tail.

**Comment by magland** [comment]
Added a legend. Here's a screenshot:
![image](https://user-images.githubusercontent.com/3679296/205926856-ff62a36d-5f67-418f-b0b9-97d0b2066c8b.png)

@ralphpeterson if this looks good you can close this issue.

**Comment by ralphpeterson** [comment]
looks great, thanks!
